apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    app: {{ template "kiali.name" . }}
    chart: {{ template "kiali.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: 20001
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: kiali
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
  {{if .Values.service.loadBalancerSourceRanges}}
  loadBalancerSourceRanges:
    {{range $rangeList := .Values.service.loadBalancerSourceRanges}}
    - {{ $rangeList }}
    {{end}}
  {{end}}
